# Site settings

title: Eric Chapdelaine 
url: "https://eric-chapdeliane.github.io"
baseurl: ""

bio-page-label: Resume

theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-1.html
theme-notes: theme-notes-1.html

# From css/rouge
rouge-theme: github

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

